"""Pytest fixtures for the entire test suite."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from eval.corpus import build_corpus
from eval.dataset import EvalDataset
from src.main import app

# ---------------------------------------------------------------------------
# API fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def client():
    """Provide a TestClient for the FastAPI app."""
    with TestClient(app) as c:
        yield c


# ---------------------------------------------------------------------------
# Sample file fixtures
# ---------------------------------------------------------------------------

@pytest.fixture()
def sample_txt(tmp_path: Path) -> Path:
    """Create a sample plain text legal document."""
    content = (
        "IN THE SUPREME COURT OF INDIA\n"
        "CIVIL APPELLATE JURISDICTION\n"
        "CIVIL APPEAL NO. 1234 OF 2024\n\n"
        "Section 123 of the Indian Contract Act, 1872\n"
        "An agreement without consideration is void.\n\n"
        "Article 14 of the Constitution of India\n"
        "The State shall not deny to any person equality before the law.\n\n"
        "Page 1 of 5\n"
        "Downloaded from Indian Kanoon\n"
    )
    p = tmp_path / "sample.txt"
    p.write_text(content, encoding="utf-8")
    return p


@pytest.fixture()
def sample_docx(tmp_path: Path) -> Path:
    """Create a sample DOCX legal document."""
    from docx import Document

    doc = Document()
    doc.add_heading("Writ Petition No. 456/2024", level=1)
    doc.add_paragraph(
        "Before the Hon'ble Mr. Justice Smith\n"
        "Rule 45-A of the Code of Civil Procedure\n"
        "Order VII Rule 11 of the CPC\n\n"
        "This is an electronic record generated by the court system.\n"
    )
    p = tmp_path / "sample.docx"
    doc.save(str(p))
    return p


@pytest.fixture()
def sample_pdf(tmp_path: Path) -> Path:
    """Create a sample text-based PDF legal document using reportlab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.pdfgen import canvas

    p = tmp_path / "sample.pdf"
    c = canvas.Canvas(str(p), pagesize=A4)
    width, height = A4

    text_lines = [
        "IN THE HIGH COURT OF KARNATAKA",
        "BENGALURU BENCH",
        "WRIT PETITION NO. 789/2024",
        "",
        "Section 123 of the Indian Contract Act",
        "Order VII Rule 11 of the CPC",
        "",
        "Article 14 of the Constitution of India",
        "Equality before the law is a fundamental right.",
        "",
        "This judgment was delivered on 15th March, 2024.",
        "Page 1 of 1",
    ]

    y = height - 2 * cm
    for line in text_lines:
        c.drawString(2 * cm, y, line)
        y -= 0.6 * cm

    c.save()
    return p


@pytest.fixture()
def sample_pdf_empty(tmp_path: Path) -> Path:
    """Create a minimal PDF with no text (simulates a scanned PDF)."""
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    p = tmp_path / "empty.pdf"
    c = canvas.Canvas(str(p), pagesize=A4)
    c.save()
    return p


@pytest.fixture()
def output_dir() -> Path:
    """Return the data/processed output directory."""
    d = Path(__file__).resolve().parent.parent / "data" / "processed"
    d.mkdir(parents=True, exist_ok=True)
    return d


# ---------------------------------------------------------------------------
# Module 10 evaluation fixtures
# ---------------------------------------------------------------------------

EVAL_DOCUMENT_ID = "0940d367554383c5"
EVAL_HIERARCHY_FILE = Path("data/hierarchy/0940d367554383c5.json")
EVAL_GOLD_DIR = Path("data/eval/gold")


@pytest.fixture(scope="session")
def eval_corpus():
    """Deterministic offline corpus used across the evaluation tests."""
    corpus = build_corpus(
        document_id=EVAL_DOCUMENT_ID,
        hierarchy_file=str(EVAL_HIERARCHY_FILE),
        seed=42,
    )
    yield corpus
    corpus.close()


@pytest.fixture(scope="session")
def eval_dataset() -> EvalDataset:
    """The grounded Contract Act gold dataset."""
    return EvalDataset.load(EVAL_GOLD_DIR / "contract_act_gold.json")


@pytest.fixture(scope="session")
def eval_items(eval_dataset) -> list:
    """The grounded evaluation items."""
    return eval_dataset.grounded_items()
